In [18]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [19]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [20]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [21]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [22]:
X=df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y=df['needs_water']

In [23]:
# stansardizing the values (means converting each values between 0 - 1)
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [24]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42, stratify=y
)

In [26]:
model=keras.Sequential([
    layers.Input(shape=(X_scaled.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [27]:
model.compile(optimizer='sgd',loss = 'binary_crossentropy',metrics= ['accuracy'])

In [28]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data = (X_test.values,y_test.values),
    epochs = 100,batch_size = 1 , verbose = 1
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.5000 - loss: 0.6665 - val_accuracy: 0.5000 - val_loss: 0.6780
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5000 - loss: 0.6593 - val_accuracy: 0.5000 - val_loss: 0.6717
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.6529 - val_accuracy: 0.5000 - val_loss: 0.6665
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5000 - loss: 0.6465 - val_accuracy: 0.5000 - val_loss: 0.6611
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5833 - loss: 0.6412 - val_accuracy: 0.7500 - val_loss: 0.6559
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5833 - loss: 0.6362 - val_accuracy: 0.7500 - val_loss: 0.6504
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6314 - val_accuracy: 0.7500 - val_loss: 0.6449
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6272 - val_accuracy: 0.7500 - val_loss: 0.6406
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 0.6234 - val_accuracy: 1.0000 - val_loss: 0.6364
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6667 - loss: 0.6195 - val_accuracy: 1.0000 - val_loss: 0.6325
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 0.6159 - val_accuracy: 1.0000 - val_loss: 0.6282
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 0.6123 - val_accuracy: 1.0000 - val_loss: 0.6242
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.6087 - val_accuracy: 1.0000 - val_loss: 0.6205
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.6053 - val_accuracy: 1.0000 - val_loss: 0.6172
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8333 - loss: 0.6018 - val_accuracy: 1.0000 - val_loss: 0.6137
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5983 - val_accuracy: 1.0000 - val_loss: 0.6107
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5946 - val_accuracy: 1.0000 - val_loss: 0.6079
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.5918 - val_accuracy: 1.0000 - val_loss: 0.6039
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.5888 - val_accuracy: 1.0000 - val_loss: 0.6005
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.5855 - val_accuracy: 1.0000 - val_loss: 0.5976
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.5821 - val_accuracy: 1.0000 - val_loss: 0.5949
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.5790 - val_accuracy: 1.0000 - val_loss: 0.5919
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8333 - loss: 0.5764 - val_accuracy: 1.0000 - val_loss: 0.5883
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.5732 - val_accuracy: 1.0000 - val_loss: 0.5849
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.5701 - val_accuracy: 1.0000 - val_loss: 0.5818
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.5664 - val_accuracy: 1.0000 - val_loss: 0.5792
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.5639 - val_accuracy: 1.0000 - val_loss: 0.5757
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.5608 - val_accuracy: 1.0000 - val_loss: 0.5726
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.5572 - val_accuracy: 1.0000 - val_loss: 0.5689
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.5541 - val_accuracy: 1.0000 - val_loss: 0.5663
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.5516 - val_accuracy: 1.0000 - val_loss: 0.5630
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.5485 - val_accuracy: 1.0000 - val_loss: 0.5599
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9167 - loss: 0.5455 - val_accuracy: 1.0000 - val_loss: 0.5567
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.5421 - val_accuracy: 1.0000 - val_loss: 0.5539
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.5393 - val_accuracy: 1.0000 - val_loss: 0.5505
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.5363 - val_accuracy: 1.0000 - val_loss: 0.5474
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.5333 - val_accuracy: 1.0000 - val_loss: 0.5442
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9167 - loss: 0.5298 - val_accuracy: 1.0000 - val_loss: 0.5414
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.5268 - val_accuracy: 1.0000 - val_loss: 0.5377
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9167 - loss: 0.5241 - val_accuracy: 1.0000 - val_loss: 0.5345
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9167 - loss: 0.5209 - val_accuracy: 1.0000 - val_loss: 0.5311
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.5180 - val_accuracy: 1.0000 - val_loss: 0.5279
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9167 - loss: 0.5151 - val_accuracy: 1.0000 - val_loss: 0.5248
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.5118 - val_accuracy: 1.0000 - val_loss: 0.5214
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.5091 - val_accuracy: 1.0000 - val_loss: 0.5186
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.5060 - val_accuracy: 1.0000 - val_loss: 0.5158
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.5030 - val_accuracy: 1.0000 - val_loss: 0.5129
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.4994 - val_accuracy: 1.0000 - val_loss: 0.5106
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.4971 - val_accuracy: 1.0000 - val_loss: 0.5071
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9167 - loss: 0.4941 - val_accuracy: 1.0000 - val_loss: 0.5039
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4912 - val_accuracy: 1.0000 - val_loss: 0.5008
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4882 - val_accuracy: 1.0000 - val_loss: 0.4976
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4847 - val_accuracy: 1.0000 - val_loss: 0.4952
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4824 - val_accuracy: 1.0000 - val_loss: 0.4920
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4796 - val_accuracy: 1.0000 - val_loss: 0.4887
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4762 - val_accuracy: 1.0000 - val_loss: 0.4858
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.4724 - val_accuracy: 1.0000 - val_loss: 0.4838
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4710 - val_accuracy: 1.0000 - val_loss: 0.4803
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4681 - val_accuracy: 1.0000 - val_loss: 0.4770
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4651 - val_accuracy: 1.0000 - val_loss: 0.4742
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.4623 - val_accuracy: 1.0000 - val_loss: 0.4714
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.4597 - val_accuracy: 1.0000 - val_loss: 0.4680
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.4565 - val_accuracy: 1.0000 - val_loss: 0.4645
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.4537 - val_accuracy: 1.0000 - val_loss: 0.4610
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.4509 - val_accuracy: 1.0000 - val_loss: 0.4585
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4486 - val_accuracy: 1.0000 - val_loss: 0.4556
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.4455 - val_accuracy: 1.0000 - val_loss: 0.4521
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4427 - val_accuracy: 1.0000 - val_loss: 0.4496
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.4404 - val_accuracy: 1.0000 - val_loss: 0.4469
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4378 - val_accuracy: 1.0000 - val_loss: 0.4439
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.4351 - val_accuracy: 1.0000 - val_loss: 0.4407
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.4321 - val_accuracy: 1.0000 - val_loss: 0.4381
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.4289 - val_accuracy: 1.0000 - val_loss: 0.4362
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.4275 - val_accuracy: 1.0000 - val_loss: 0.4329
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.4248 - val_accuracy: 1.0000 - val_loss: 0.4295
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.4220 - val_accuracy: 1.0000 - val_loss: 0.4272
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4198 - val_accuracy: 1.0000 - val_loss: 0.4241
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.4172 - val_accuracy: 1.0000 - val_loss: 0.4212
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.4143 - val_accuracy: 1.0000 - val_loss: 0.4178
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4121 - val_accuracy: 1.0000 - val_loss: 0.4148
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.4096 - val_accuracy: 1.0000 - val_loss: 0.4116
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4073 - val_accuracy: 1.0000 - val_loss: 0.4091
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4046 - val_accuracy: 1.0000 - val_loss: 0.4072
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.4019 - val_accuracy: 1.0000 - val_loss: 0.4055
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.4001 - val_accuracy: 1.0000 - val_loss: 0.4028
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.3977 - val_accuracy: 1.0000 - val_loss: 0.3996
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3953 - val_accuracy: 1.0000 - val_loss: 0.3976
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3929 - val_accuracy: 1.0000 - val_loss: 0.3954
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3910 - val_accuracy: 1.0000 - val_loss: 0.3927
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3887 - val_accuracy: 1.0000 - val_loss: 0.3896
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.3862 - val_accuracy: 1.0000 - val_loss: 0.3868
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.3841 - val_accuracy: 1.0000 - val_loss: 0.3838
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.3818 - val_accuracy: 1.0000 - val_loss: 0.3817
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3796 - val_accuracy: 1.0000 - val_loss: 0.3787
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3773 - val_accuracy: 1.0000 - val_loss: 0.3767
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.3754 - val_accuracy: 1.0000 - val_loss: 0.3746
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.3733 - val_accuracy: 1.0000 - val_loss: 0.3718
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.3713 - val_accuracy: 1.0000 - val_loss: 0.3696
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.3690 - val_accuracy: 1.0000 - val_loss: 0.3673
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.3672 - val_accuracy: 1.0000 - val_loss: 0.3646